version: "3"
services:
  web:
    image: flask-project
    ports:
      - "5000:5000"
    volumes:
      - "${dir}:${dir}"
  db:
    image: mysql:8.0.28
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: testingtesting123
      MYSQL_ROOT_PASSWORD: Parole1
    volumes:
      - "${dir}/database:/docker-entrypoint-initdb.d/:ro"
  ngi:
    image: nginx
    ports:
      - "1234:80"
    volumes:
      - "${dir}/nginx:/etc/nginx/conf.d/"
